info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

# INICIO - SPRING PROPERTIES
spring:
  profiles:
    active: ${ENVIRONMENT:@spring.profiles.active@}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    problemdetails:
      enabled: true
  jackson:
    default-property-inclusion: NON_NULL